# Generated by Django 2.0.3 on 2018-05-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='user',
            new_name='emplyoee',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='deadline',
        ),
    ]
