# Generated by Django 2.0.3 on 2018-05-13 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0004_auto_20180509_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_employee',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='day',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='employee',
        ),
        migrations.AddField(
            model_name='assignment',
            name='end_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='days',
            field=models.ManyToManyField(to='employee_profile.Day'),
        ),
        migrations.AddField(
            model_name='employee',
            name='grades',
            field=models.ManyToManyField(to='employee_profile.Grade'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_profile.Employee'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(max_length=50),
        ),
    ]
