# Generated by Django 2.0.3 on 2018-05-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0005_auto_20180513_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee',
            new_name='user',
        ),
    ]
