# Generated by Django 2.0.3 on 2018-05-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0007_auto_20180516_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='end_date',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
